name: praat-environment

channels:
  - conda-forge
dependencies:
  - python>=3.5
  - numpy
  - pandas
  - praat-parselmouth
  - glob2
  - pip
  - pip:
    - praat_parselmouth-0.3.2-cp34-cp34m-manylinux1_x86_64.whl
